name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:


# Create flake8 configuration file
cat > .flake8 << 'EOF'
[flake8]
max-line-length = 88
exclude = venv,.git,__pycache__,.github
ignore = E501
